wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      4: 3.8.5
      5: 0.10.30
      8:
      - 5
batch_size:
  desc: null
  value: 286
criterion:
  desc: null
  value: binary_cross_entropy
epochs:
  desc: null
  value: 100000
learning_rate:
  desc: null
  value: 0.063238104981779
momentum:
  desc: null
  value: 0.9
optimizer:
  desc: null
  value: adam
scheduler:
  desc: null
  value: Cosine Annealing
use_SAM:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 1.0e-05
