wandb_version: 1

batch_size:
  value: 2
criterion:
  value: binary_cross_entropy
epochs:
  value: 88
learning_rate:
  value: 0.0017802544126392706
momentum:
  value: 0.9
optimizer:
  value: adam
scheduler:
  value: Cosine Annealing
use_SAM:
  value: false
weight_decay:
  value: 1.0e-05
