wandb_version: 1

batch_size:
  value: 56
criterion:
  value: binary_cross_entropy
epochs:
  value: 595
learning_rate:
  value: 0.022169983564881108
momentum:
  value: 0.9
optimizer:
  value: adam
scheduler:
  value: null
use_SAM:
  value: false
weight_decay:
  value: 1.0e-05
