wandb_version: 1

batch_size:
  value: 26
criterion:
  value: binary_cross_entropy
epochs:
  value: 1
learning_rate:
  value: 0.03663352476979905
momentum:
  value: 0.9
optimizer:
  value: adam
scheduler:
  value: Cosine Annealing
use_SAM:
  value: false
weight_decay:
  value: 1.0e-05
