wandb_version: 1

batch_size:
  value: 26
criterion:
  value: binary_cross_entropy
epochs:
  value: 937
learning_rate:
  value: 0.015092859252445674
momentum:
  value: 0.9
optimizer:
  value: adam
scheduler:
  value: null
use_SAM:
  value: false
weight_decay:
  value: 1.0e-05
