wandb_version: 1

batch_size:
  value: 51
criterion:
  value: binary_cross_entropy
epochs:
  value: 67
learning_rate:
  value: 0.09573864412575005
momentum:
  value: 0.9
optimizer:
  value: adam
scheduler:
  value: Cosine Annealing
use_SAM:
  value: false
weight_decay:
  value: 1.0e-05
