wandb_version: 1

batch_size:
  value: 25
criterion:
  value: binary_cross_entropy
epochs:
  value: 831
learning_rate:
  value: 0.030015232809811616
momentum:
  value: 0.9
optimizer:
  value: adam
scheduler:
  value: Cosine Annealing
use_SAM:
  value: false
weight_decay:
  value: 1.0e-05
